### ISSUE TITLE
Mettre en place les outils de CI/qualité de code sur notre fork

### ISSUE THREAD

**Issue by Em-AK** [CDJ11/CDJ#10]
* travis (via compte GH)
* code climate (via compte GH)
* gemnasium (compte séparé)

=> besoin de plus de droits au sein de l'organisation ou laisser le CDJ créer les différents comptes sur ces services

**Comment by CDAude** [comment]
Integration des services Travis CI et CodeClimate faite. Si cela ne correspond pas, quel droit je dois te mettre sous GitHub pour que tu puisses faire le necessaire. Pour Gemnasium, je ne l'ai pas fait car il vont bientot arreter de fonctionner (https://gemnasium.com/blog/gemnasium-is-acquired-by-gitlab/). Est-ce que ca vaux le coup de les créer pour autant?

**Comment by Em-AK** [comment]
Oui en effet pas besoin de mettre en place Gemnasium.
Une nouvelle fonctionalité de Github permet de recevoir des alertes lorsqu'une dépendance du projet est concernée par une faille de sécurité connue:
https://github.com/CDJ11/CDJ/network/dependencies

Pour que je puisse finaliser la connection des différents services externes il me faut un accès de niveau Admin sur le repo.
https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by CDAude** [comment]
Bonjour,

Je Viens de te rajouter en tant qu’Admin au niveau du Repo.

Cordialement


Patrice Gallardo │Chef de projet informatique
Département de l’Aude - Service informatique
Pôle ressources / Direction de l’information
Tél. : 04 68 11 06 37
patrice.gallardo@aude.fr<mailto:patrice.gallardo@aude.fr>

De : Emilien [mailto:notifications@github.com]
Envoyé : dimanche 4 mars 2018 17:16
À : CDJ11/CDJ
Cc : GALLARDO Patrice; State change
Objet : Re: [CDJ11/CDJ] Mettre en place les outils de CI/qualité de code sur notre fork (#10)


Oui en effet pas besoin de mettre en place Gemnasium.
Une nouvelle fonctionalité de Github permet de recevoir des alertes lorsqu'une dépendance du projet est concernée par une faille de sécurité connue:
https://github.com/CDJ11/CDJ/network/dependencies

Pour que je puisse finaliser la connection des différents services externes il me faut un accès de niveau Admin sur le repo.
https://help.github.com/articles/repository-permission-levels-for-an-organization/
