### ISSUE TITLE
Pouvoir supprimer une idée que j'ai créée

### ISSUE THREAD

**Issue by clairezed** [CDJ11/CDJ#26]

**Comment by clairezed** [comment]
@CDAude Un auteur peut supprimer l'une de ses idées sans restriction ? 
Par exemple, est-il possible de supprimer une idée : 
- qui a été commentée ?
- qui a reçu des votes ?
- qui a reçu un certain seuil de votes ? (pr exemple, il y a un seuil de votes à partir duquel une idée n'est plus modifiable)

Pour info, pour le moment, même un administrateur ne peut pas supprimer une idée.

**Comment by CDAude** [comment]
Bonjour,

En effet, nous avons confirmé que la logique à mettre en place serait :

-          Il est possible qu’un utilisateur puisse supprimer une idée à condition que :

o   Ce soit lui l’émetteur de l’idée

o   Que cette idée n’ait fait l’objet d’aucune interaction avec d’autres utilisateurs (donc ni commentaire, ni like)

Merci d’avance

Cordialement


Patrice Gallardo │Chef de projet informatique
Département de l’Aude - Service informatique
Pôle ressources / Direction de l’information
Tél. : 04 68 11 06 37
patrice.gallardo@aude.fr<mailto:patrice.gallardo@aude.fr>

De : Claire Zuliani [mailto:notifications@github.com]
Envoyé : vendredi 23 mars 2018 14:52
À : CDJ11/CDJ
Cc : GALLARDO Patrice; Mention
Objet : Re: [CDJ11/CDJ] Pouvoir supprimer une idée que j'ai créée (#26)


@CDAude<https://github.com/cdaude> Un auteur peut supprimer l'une de ses idées sans restriction ?
Par exemple, est-il possible de supprimer une idée :

  *   qui a été commentée ?
  *   qui a reçu des votes ?
  *   qui a reçu un certain seuil de votes ? (pr exemple, il y a un seuil de votes à partir duquel une idée n'est plus modifiable)

Pour info, pour le moment, même un administrateur ne peut pas supprimer une idée.
