### ISSUE TITLE
Déploiement avec capistrano

### ISSUE THREAD

**Issue by clairezed** [CDJ11/CDJ#57]
Mettre à jour la procédure de déploiement pour qu'elle se fasse avec capistrano 

Cf https://github.com/consul/installer

## Notes 

Si problème avec la précompiltion des assets, voir https://coderwall.com/p/aridag/only-precompile-assets-when-necessary-rails-4-capistrano-3

**Comment by clairezed** [comment]
@CDAude pourrais-je avoir des droits admin sur le serveur (même temporairement) pour avoir accès aux "Settings" et faire en sorte que le serveur de déploiement ait accès au code sur github, pour faciliter le déploiement ?

**Comment by clairezed** [comment]
@CDAude Pardon : des droits admin sur **ce projet github**, pas sur le serveur !

**Comment by CDAude** [comment]
Bonjour,

Vous avez été promu admin.

Cordialement


Patrice Gallardo │Chef de projet informatique
Département de l’Aude - Service informatique
Pôle ressources / Direction de l’information
Tél. : 04 68 11 06 37
patrice.gallardo@aude.fr<mailto:patrice.gallardo@aude.fr>

De : Claire Zuliani [mailto:notifications@github.com]
Envoyé : jeudi 12 juillet 2018 12:04
À : CDJ11/CDJ
Cc : GALLARDO Patrice; Mention
Objet : Re: [CDJ11/CDJ] Déploiement avec capistrano (#57)


@CDAude<https://github.com/CDAude> Pardon : des droits admin sur ce projet github, pas sur le serveur !
