### ISSUE TITLE
Management des membres du conseil d'animation (Animator)

### ISSUE THREAD

**Issue by clairezed** [CDJ11/CDJ#63]
- [x] un superAdmin (Département) peut lister tous les membres du conseil d'animation
- [x] un superAdmin (Département) peut donner et supprimer le rôle de membre du CA à un utilisateur inscrit
- [x] un superAdmin (Département) peut afficher les informations personnelles des utilisateurs
- [x] un superAdmin (Département) et un membre du CA peuvent réinitialiser le mot de passe d'un utilisateur

**Comment by clairezed** [comment]
[On avait abordé en partie cette question à notre dernier rdv, mais je préfère revérifier par écrit, j'ai l'impression que mes notes sont incomplètes]

@CDAude Concernant la possibilité de créer, modifier et supprimer un membre du CA : actuellement, ce que permet consul est de donner un rôle (modérateur, manager, admin...) / supprimer un rôle d'un utilisateur existant.  
C'est ce que j'ai commencé à mettre en place pour les membres du CA. 

En termes de modification, la seule modification actuellement possible (dans la partie management, après avoir vérifier via numéros de documents) est la réinitialisation du mot de passe.
Je peux également ajouter cette fonctionnalité (sans la vérification) aux membres du CA.

Par contre, il n'est actuellement pas possible, même pour un admin, de créer ou modifier un utilisateur (en remplissant un formulaire comme celui d'inscription, par exemple). Seul un utilisateur peut modifier ses propres infos. **Est-ce que c'est une fonctionnalité sur laquelle vous comptez ?**

Il n'est pas non plus possible, actuellement, d'afficher les informations complémentaires de l'utilisateur (âge, adresse, genre, téléphone...). **Voulez-vous rendre ses infos visibles en back office ? Aux membres du CA ? Aux admins ? Aux deux ? 
Si oui, ne pas oublier d'en parler dans les infos à rédiger sur la protection de la vie privée (RGPD).**

Enfin, et histoire d'être sûre : actuellement, dans la partie Management, il est possible de mener des actions au nom d'un utilisateur, comme si c'était un autre utilisateur qui les effectuait (créer un projet, soutenir un projet...). **Est-ce une fonctionnalité à conserver, et à ajouter aussi dans la gestion des utilisateurs ?**

**Comment by clairezed** [comment]
@CDAude je profite de vous voir réactf sur un autre ticket pour remettre en avant celui-ci ! Quand pensez-vous pouvoir me faire un retour ? (afin que j'organise mes tâches)

**Comment by CDAude** [comment]
Bonjour,

Voici mes réponses:
- "possibilité de créer, modifier et supprimer un membre du CA" => seul un agent du département ("SuperAdmin") doit pouvoir faire ce type d'action
- créer ou modifier un utilisateur => On peut s'en passer: on reroutera les utilisateurs vers le formulaire et on leur indiquera comment modifier leur détails. La seule inconnue est comment il peuvent modifier leur email (recréation de compte?)
- Afficher les informations complémentaires de l'utilisateur => Pas de problème mais peut-on alors se prevoir une petite interface qui extrait ces infos pour les SuperAdmin (ou un accès aux tables de la Base de données). On en parlerai alors dans la partie RGPD pour justifier le besoin de statistiques
- partie Management, il est possible de mener des actions au nom d'un utilisateur => Non pas souhaité du tout. Cela pourrait faire du sens pour les personnes qui n'ont pas accès à Internet mais si on a ce cas, ces personnes pourront toujours passer par le CA pour créer des idées, commentaires et réponse. Il leur manquera juste la partie Vote, soutien mais cela devrait être marginal.

Merci

**Comment by clairezed** [comment]
J'ai actualisé la description des tâches de ce [ticket](https://github.com/CDJ11/CDJ/issues/63#issue-335391271) en fonction de ces derniers échanges. Je vous laisse me dire si ça ne correspond pas à ce qui est attendu

**Comment by CDAude** [comment]
Ok pour moi
