### ISSUE TITLE
Menu admin des membres du CA

### ISSUE THREAD

**Issue by clairezed** [CDJ11/CDJ#66]
- [x] Interdire l'accès au pages superflues
- [x]  enlever les liens vers les pages superflues
- [x] créer le menu "communication"

**Comment by clairezed** [comment]
@CDAude Est-ce qu'on calque l'organisation des rubriques admin des administrateurs sur celles des membres du CA ? 
A vue de nez, j'ai l'impression que ce serait le plus simple, mais j'attends votre retour.

PS : pour info, je travaille toute la semaine sur CDJ, mais serai en déplacement la semaine qui suit

**Comment by CDAude** [comment]
Bonjour,
Si calquer l'organisation des rubriques admin des agents du département (administrateur) sur celle des membres du CA est plus simple a mettre en oeuvre d'un point de vue technique et que ça ne remet pas trop en cause le modèle Consul, alors ok. Sinon ce n'est pas grave. nous l'utiliserons dans tous les cas que très peu.
Merci d'avance
Cordialement
