### ISSUE TITLE
Importer les cantons du département dans les géozones

### ISSUE THREAD

**Issue by Em-AK** [CDJ11/CDJ#8]
* définition des géozones en base de donnée
  * via le fichier db/seeds.rb (ou une extenstion custom de ce fichier)
* affichage de la carte des cantons

**Comment by CDAude** [comment]
Liste des cantons (format insert SQL, csv ou html)




[extract_geozone_sql.txt](https://github.com/CDJ11/CDJ/files/1766753/extract_geozone_sql.txt)

[extract_geozone_csv.txt](https://github.com/CDJ11/CDJ/files/1766755/extract_geozone_csv.txt)

[extract_geozone_html.txt](https://github.com/CDJ11/CDJ/files/1766756/extract_geozone_html.txt)
